# UNVM - Universal Node Version Manager

[![CMake Multi-Platform Build](https://github.com/Scriptor25/unvm/actions/workflows/cmake.yaml/badge.svg)](https://github.com/Scriptor25/unvm/actions/workflows/cmake.yaml)

## About

This project is heavily inspired by other already existing solutions, with one key difference: it only requires usermode
permissions and access. This is especially important when working with devices that do not give every user full system
access, e.g. workplace or office devices, or even non-rooted mobile devices.

## Building

The project uses cmake for generating build files. You need to have a generator and a toolchain installed. Following
configurations are automatically built in a workflow:

- Windows x64, Visual Studio 17 2022, MSVC
- Windows x64, Ninja, Clang
- Linux x64, Ninja, GCC
- Linux x64, Ninja, Clang
- Darwin ARM64, Ninja, GCC
- Darwin ARM64, Ninja, Clang

You have to have the following dependencies installed:

- LibArchive
- OpenSSL

### Example: Fedora Linux 43

```shell
git clone --depth 1 --single-branch https://github.com/Scriptor25/unvm.git
```

```shell
cmake -S unvm -B build -G Ninja
```

```shell
cmake --build build --parallel
```

## Usage

To get a list of available commands, use the program without arguments:

```shell
unvm
```

Version names can be:

- `latest`: the latest version
- `lts`: the latest long-term-support version
- `v<X>[.<Y>[.<Z>]]`: specify version, either latest major, latest minor or exact
- latest long-term-support version by name, e.g. `Krypton` (not case-sensitive)

Available commands are:

- `list [available]`: list all installed packages, or all online available. A `*` marks the one currently active.
- `install <version>`: install a package by version name.
- `remove <version>`: removes a package by version name.
- `use <version>|none`: select a packages by version name, and set it to be the active instance. When passing `none` for
  the
  version, the current active instance is deactivated, which effectively deactivates node on your system.

## Configuration

Depending on the system, a configuration file is generated by default in the application data or configuration
directory.

- Windows: `%APPDATA%\\unvm\\config.json`
- Linux: `$XDG_CONFIG_HOME/unvm/config.json` or `$HOME/.config/unvm/config.json`

This configuration file controls where the versions are installed to, and where the active instance directory is linked
to. It also saves the state of the installation, so what versions are currently installed and which one is currently
active.
